config/routes.rb
ComeHome::Application.routes.draw do
  get "geolocation/reverse_geocode"

  get 'users/edit'

  root :to => 'home#index'
  match '/person' => 'home#person'

  match '/login' => 'authentications#login'
  match '/new' => 'authentications#new'
  match '/logout' => 'authentications#destroy'

  match '/profile' => 'users#edit', :via => :get, :as => :show_profile
  match '/profile' => 'users#save', :via => :post, :as => :update_profile

  match '/auth/failure' => 'authentications#failure'
  match '/auth/:provider/callback' => 'authentications#create'

  match '/reverse_geocode' => 'geolocation#reverse_geocode'

end

app/models/identity.rb
class Identity
  include MongoMapper::Document
  include OmniAuth::Identity::Models::MongoMapper

  key :email, String
  key :password_digest, String

  validates_presence_of :email
  validates_uniqueness_of :email

  belongs_to :user
end

app/models/user.rb
require 'open-uri'

class User
  include MongoMapper::Document
  include Geocoder::Model::MongoMapper
  include Paperclip::Glue

  OCCUPATIONS = %w[
    Accountant
    Designer
    Programmer
    Lawyer
  ]

  key :provider, String
  key :uid, String
  key :email, String
  key :full_name, String
  key :occupation, String
  key :location, String
  key :coords, Array

  key :photo_file_name, String
  key :photo_file_size, Integer
  key :photo_content_type, String

  has_attached_file :photo, :styles => {
    :grid => '320x320#',
    :large => '1024x768>'
  }, :processors => [:cropper]

  timestamps!

  geocoded_by :location, :coordinates => :coords do |obj, results|
    if geo = results.first
      obj.coords = [geo.latitude, geo.longitude]
      obj.location = "#{geo.city}, #{geo.country}"
    end
  end

  after_validation :geocode
  after_update :reprocess_photo, :if => :cropping?

  ensure_index [[:coords, '2d']]
  
  validates_presence_of :provider
  validates_presence_of :uid
  validates_inclusion_of :occupation, :in => OCCUPATIONS, :allow_blank => true
  validates_uniqueness_of :uid, :scope => :provider

  validates_attachment :photo, :size => {:less_than => 2.megabyte},
    :content_type => {:content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif']}

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessible :provider, :uid, :full_name, :occupation, :location, :photo,
    :crop_x, :crop_y, :crop_w, :crop_h

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def photo_geometry(style=:original)
    return unless photo?
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(photo.path(style))
  end

  def self.from_omniauth (auth)
    find_by_provider_and_uid(auth['provider'], auth['uid']) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth (auth)
    User.new.tap do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.full_name = auth['info']['name']
      user.email = auth['info']['email']
      user.location = auth['info']['location']
      user.occupation = auth['info']['occupation']

      # this should go somewhere else
      if auth['provider'] == 'facebook'
        user.set_photo_from_url("http://graph.facebook.com/#{user.uid}/picture?type=large")
      end
      
      user.save
    end
  end

  def set_photo_from_url(url)
    temp = Tempfile.new(url.parameterize)
    temp.binmode
    temp.write(open(url).read)
    temp.flush
    self.photo = temp
  end

  private

  def reprocess_photo
    photo.reprocess!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def new
    @identity = env['omniauth.identity']
  end

  def failure
    render :new
  end
  
  def create
    auth = request.env['omniauth.auth']
    user = User.from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to :show_profile
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/geolocation_controller.rb
class GeolocationController < ApplicationController
  def reverse_geocode
    best_match = Geocoder.search("#{params[:lat]}, #{params[:lng]}").first
    render :text => "#{best_match.city}, #{best_match.country}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    query = User.sort(:created_at.desc)

    if session[:user_id]
      @users = query.all(:id => {:$ne => session[:user_id]})
    else
      @users = query.all
    end

    @mapData = query.where(:coords => {:$size => 2}).to_json(:only => [:full_name, :coords])
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env['omniauth.identity']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def crop
  end

  def save
    if current_user.update_attributes(params[:user])
      flash[:notice] = 'Profile updated!'
      if params[:user][:photo].blank?
        redirect_to :show_profile
      else
        render :action => :crop
      end
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def development?
    ENV['RAILS_ENV'] == 'development'
  end

  def typogrify (*args, &block)
    if block_given?
      Typogruby.improve(capture(&block)).html_safe
    else
      Typogruby.improve(args.first).html_safe
    end
  end

  def flash_class(level)
    case level
    when :notice then 'alert-success'
    when :error then 'alert-error'
    when :alert then 'alert-alert'
    end
  end

  def has_error(model, *keys)
    return unless model && model.invalid?
    (keys.map {|k| model.errors.include?(k)}).any?
  end

  def field_error(model, key)
    return if !model || model.valid? || !model.errors.include?(key)
    model.errors.get(key).first
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
  def authenticated?
    !!session[:user_id]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/login.slim
.row 
  .span6.offset3
    == render "identities/login_form"

app/views/authentications/new.html.slim
.row 
  .span6.offset3
    == render "identities/register_form"

app/views/geolocation/reverse_geocode.html.slim
h1 Geolocation#reverse_geocode
p Find me in app/views/geolocation/reverse_geocode.html.slim

app/views/home/index.html.slim
- content_for :app_data do
  javascript:
    var mapData = #{{@mapData}};

.page-header
  h1= typogrify("Who's coming home?")

  .btn-toolbar
    ul.btn-group
      li.btn.btn-large.active
        a href="#who" data-toggle="tab"
          i.icon-th-large
      li.btn.btn-large
        a href="#where" data-toggle="tab"
          i.icon-map-marker

.tab-content
  #who.tab-pane.fade.in.active
    ul.thumbnails.people
      - if authenticated?
        li.span2 
          a.thumbnail#self href="#{show_profile_path}"
            img src="#{current_user.photo.url(:grid)}"
      - else
        li.span2 
          a.thumbnail#sign-up href="#{new_path}"
            img src="#{asset_path 'add-big.png'}"
      - @users.each do |u|
        li.span2
          a.thumbnail.person href="#"
            img src="#{u.photo.url(:grid)}"
  #where.tab-pane.fade
    #map

app/views/home/person.html.slim
.page-header
  h1 Who's coming?
  
.row.person
  .span3
    img src="http://placehold.it/160x160"
  
  .span4
    h2 Mike Martin
    h3 Web Designer

    p Living in Vancouver, BC
  
    a.btn href="/" 
      i.icon-arrow-left
      |  Back
      
      

app/views/identities/_login_form.html.slim
== form_tag "/auth/identity/callback", :class => 'form-horizontal' do
  == field_set_tag "Already have an account?" do
    - if @error
      p.errors= @error
    .control-group
      = label_tag :auth_key, "Email", :class => "control-label"
      .controls
        = email_field_tag :auth_key, @identity.try(:email)
    .control-group
      = label_tag :password,  "Password", :class => "control-label"
      .controls
        = password_field_tag :password, nil
  .form-actions
    = button_tag "Login", :class => "btn btn-primary"

app/views/identities/_register_form.html.slim
== form_tag "/auth/identity/register", :class => 'form-horizontal' do
  == field_set_tag "I'm coming home!" do
    - if @identity && @identity.errors.any?
        .alert.alert-error Oops! Please correct the errors below
    .control-group
      a#connect-with-facebook.btn.btn-large.btn-primary href="/auth/facebook" Login with Facebook
      p Or create an account
    div class="control-group #{'error' if has_error(@identity, :email)}"
      = label_tag :email, "Email", :class => "control-label"
      .controls
        = email_field_tag :email, @identity.try(:email)
        p.help-inline= field_error(@identity, :email)
    div class="control-group #{'error' if has_error(@identity, :password, :password_digest)}"
      = label_tag :password, "Password", :class => "control-label"
      .controls
        = password_field_tag :password, nil
        p.help-inline= field_error(@identity, :password_digest)
    div class="control-group #{'error' if has_error(@identity, :password, :password_digest)}"
      = label_tag :password_confirmation, "Confirm password", :class => "control-label"
      .controls
        = password_field_tag :password_confirmation, nil
        p.help-inline= field_error(@identity, :password_digest)
    .control-group
      label.control-label for="question" What was the name of the sod farm?
      .controls
        input name="question" type="text"
    .form-actions
      = button_tag "Sign Up", :class => "btn btn-primary"

app/views/identities/new.html.slim
= render "register_form"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    title= content_for?(:title) ? yield(:title) : "Home"
    = csrf_meta_tags
    link href="/favicon.ico" rel="shortcut icon"
    = stylesheet_link_tag "application", :media => "all"
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDN6cCLL__NG0EVA4-vhGTSJeoJEtOOpZw&libraries=places&sensor=false"
    = yield :app_data
  body
    .navbar.navbar-fixed-top
      .navbar-inner 
        .container
          a#date-location href="#" August 9th to 13th, 2012
          .nav-collapse
            ul.nav
              li
                a href="/" Home 
              - if authenticated? 
                li
                  a href="#{show_profile_path}" Profile 
                li
                  a href="#{logout_path}" Logout 
              - else
                li
                  a href="#{login_path}" Login
                li
                  a href="#{new_path}" Sign Up

    .container
      header.masthead
        .inner
          h1 
            a href="/"= typogrify("St. Shott's Come Home Year")
          p.lead
            ' It's been a while, check out 
            a href="#who" data-toggle="tab" who's coming home 
            ' and 
            a href="#where" data-toggle="tab" where they are now
            '!
          
      - if development?
        .alert.alert-info
          -if authenticated?
            a href="#{logout_path}" logout
            '
            a href="#{show_profile_path}" profile
          - else
            a href="#{login_path}" login
          ' 
          ' current user:
          = current_user.inspect
      .content
        = yield
      footer
        markdown:
          A project by [Mike Martin](http://michaelmartin.ca) and [Alexis Georges](http://albatross.io)
    = javascript_include_tag "application"

app/views/users/_profile_form.html.slim
== render '/message'

.row
  .span2
    .thumbnail
      img src="#{current_user.photo.url(:grid)}"
  .span10
    == form_tag update_profile_path, :multipart => true, :class => 'form-inline well' do
      == field_set_tag 'Edit your info' do
        - if current_user.errors.any?
          .alert.alert-error Oops! Please correct the errors below
        == fields_for current_user do |f|
          .control-group
            = f.label :full_name, :class => 'control-label'
            .controls
              = f.text_field :full_name, :class => 'input-xlarge'
          .control-group
            = f.label :location, :class => 'control-label'
            .controls
              .input-append
                = f.text_field :location, :class => 'input-xlarge', :id => 'searchLocation'
                a.btn#getLocation
                  i.icon-map-marker
          .control-group
            = f.label :occupation, :class => 'control-label'
            .controls
              = f.select :occupation, options_for_select(User::OCCUPATIONS, current_user.occupation)
              p.help-inline= field_error(current_user, :occupation)
          div class="control-group #{'error' if has_error(current_user, :photo_file_size)}"
            = f.label :photo, :class => 'control-label'
            .controls
              = f.file_field :photo
              span.alert.alert-info You can adjust your photo on the next step
              p.help-block= field_error(current_user, :photo_file_size)
      .form-actions
        = button_tag 'Save', :class => 'btn btn-primary'

app/views/users/crop.html.slim
- content_for :app_data do
  - if current_user.photo?
    javascript:
      var photoRatio = #{current_user.photo_geometry(:original).width} / #{current_user.photo_geometry(:large).width};

== form_for current_user, :method => :post, :url => update_profile_path do |f|
  == field_set_tag 'Edit your profile photo' do
    #canvas
      img src="#{current_user.photo.url(:large)}"
    = f.hidden_field 'crop_x'
    = f.hidden_field 'crop_y'
    = f.hidden_field 'crop_w'
    = f.hidden_field 'crop_h'
    .form-actions
      = button_tag "Save", :class => "btn btn-primary"

app/views/users/edit.html.slim
== render "profile_form"